# Generated by Django 3.1.7 on 2021-04-08 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenthi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
