# Generated by Django 3.1.7 on 2021-04-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenthi', '0004_auto_20210409_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='privacy',
            field=models.BooleanField(default=True),
        ),
    ]
