# Generated by Django 3.1.7 on 2021-04-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenthi', '0005_todo_privacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('product', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('link', models.CharField(default='No link available', max_length=50)),
            ],
        ),
    ]
