# Generated by Django 3.1.7 on 2021-04-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenthi', '0006_grid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
